// This file renders comparison results for the terminal and for Markdown.
package report

import (
	"encoding/json"
	"fmt"
	"io"
	"strings"

	"github.com/zelvior/lensyxe/internal/compare"
)

// RenderCompareJSON writes the comparison as indented JSON.
func RenderCompareJSON(w io.Writer, res *compare.Result) error {
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	if err := enc.Encode(res); err != nil {
		return fmt.Errorf("render compare json: %w", err)
	}
	return nil
}

// RenderCompareMarkdown writes the comparison as a Markdown document sized for
// a pull-request comment: verdict first, then what changed and why it matters.
func RenderCompareMarkdown(w io.Writer, res *compare.Result) error {
	if res == nil {
		return fmt.Errorf("render compare markdown: nil result")
	}
	var b strings.Builder

	fmt.Fprintf(&b, "# Engineering health: `%s` → `%s`\n\n",
		escapePipes(res.A.ShortSHA), escapePipes(res.B.ShortSHA))
	fmt.Fprintf(&b, "| | A (`%s`) | B (`%s`) |\n| --- | ---: | ---: |\n",
		escapePipes(res.A.Ref), escapePipes(res.B.Ref))
	fmt.Fprintf(&b, "| **Health score** | **%.1f** (%s) | **%.1f** (%s) |\n",
		res.ScoreA, res.GradeA, res.ScoreB, res.GradeB)
	b.WriteString("\n")
	fmt.Fprintf(&b, "**Delta: %+.1f.** %s\n\n", res.ScoreDelta, res.Verdict)

	// See RenderCompare for why this composite is not on the same scale as
	// `lensyxe analyze`. Both sides are measured identically, so the delta stands.
	b.WriteString("> **Note.** Maintainability is not measured in a comparison. Both revisions\n" +
		"> are exported with `git archive`, which produces no Git history, so that\n" +
		"> dimension's weight is redistributed across the others. The absolute scores\n" +
		"> here are therefore not comparable with `lensyxe analyze` on the same commit.\n" +
		"> The delta is: both revisions are measured the same way.\n\n")

	if len(res.Metrics) > 0 {
		b.WriteString("## Metric deltas\n\n")
		b.WriteString("| Metric | A | B | Delta | Direction |\n")
		b.WriteString("| --- | ---: | ---: | ---: | --- |\n")
		for _, m := range res.Metrics {
			arrow := "→"
			switch {
			case m.Better > 0:
				arrow = "improved"
			case m.Better < 0:
				arrow = "regressed"
			}
			fmt.Fprintf(&b, "| %s | %s | %s | %s | %s |\n",
				escapePipes(m.Label),
				formatValue(m.A, m.Unit), formatValue(m.B, m.Unit),
				fmt.Sprintf("%+.1f", m.Delta), arrow)
		}
		b.WriteString("\n")
	}

	if len(res.RisksAdded) > 0 {
		fmt.Fprintf(&b, "## New risks (%d)\n\n", len(res.RisksAdded))
		for _, r := range res.RisksAdded {
			fmt.Fprintf(&b, "### %s %s %s\n\n",
				r.Severity.Emoji(), strings.ToUpper(string(r.Severity)), escapePipes(r.Title))
			if r.Subject != "" {
				fmt.Fprintf(&b, "Subject: `%s`\n\n", escapePipes(r.Subject))
			}
			b.WriteString(r.Detail + "\n\n")
			if len(r.Evidence) > 0 {
				b.WriteString("| Evidence | Measurement | Value |\n")
				b.WriteString("| --- | --- | ---: |\n")
				for _, e := range r.Evidence {
					value := "-"
					if e.Value != nil {
						value = fmt.Sprintf("%.2f", *e.Value)
					}
					fmt.Fprintf(&b, "| %s | %s | %s |\n",
						escapePipes(e.Label), escapePipes(e.Detail), value)
				}
				b.WriteString("\n")
			}
			if r.Recommendation != "" {
				b.WriteString("**Recommendation**: " + r.Recommendation + "\n\n")
			}
		}
	}

	if len(res.RisksChanged) > 0 {
		fmt.Fprintf(&b, "## Changed risks (%d)\n\n", len(res.RisksChanged))
		b.WriteString("| Risk | Severity | Impact | Delta |\n")
		b.WriteString("| --- | --- | ---: | ---: |\n")
		for _, c := range res.RisksChanged {
			fmt.Fprintf(&b, "| %s | %s → %s | %.1f → %.1f | %+.1f |\n",
				escapePipes(c.Title),
				strings.ToUpper(string(c.Severity)), strings.ToUpper(string(c.After)),
				c.ImpactA, c.ImpactB, c.Delta)
		}
		b.WriteString("\n")
	}

	if len(res.RisksResolved) > 0 {
		fmt.Fprintf(&b, "## Resolved risks (%d)\n\n", len(res.RisksResolved))
		for _, r := range res.RisksResolved {
			fmt.Fprintf(&b, "- %s %s\n", r.Severity.Emoji(), escapePipes(r.Title))
		}
		b.WriteString("\n")
	}

	if len(res.RisksAdded) == 0 && len(res.RisksResolved) == 0 && len(res.RisksChanged) == 0 {
		b.WriteString("No risk changes between these revisions.\n\n")
	}

	b.WriteString("---\n\n")
	fmt.Fprintf(&b, "_Generated by Lensyxe %s, schema v%s. Deterministic local analysis._\n",
		res.Version, res.SchemaVersion)

	if _, err := io.WriteString(w, b.String()); err != nil {
		return fmt.Errorf("render compare markdown: %w", err)
	}
	return nil
}

// formatValue renders a metric value with its unit for Markdown.
func formatValue(v float64, unit string) string {
	if v == float64(int64(v)) {
		if unit != "" {
			return fmt.Sprintf("%d %s", int64(v), unit)
		}
		return fmt.Sprintf("%d", int64(v))
	}
	s := fmt.Sprintf("%.2f", v)
	if unit != "" {
		return s + " " + unit
	}
	return s
}

// RenderCompare writes the comparison as a terminal report.
func RenderCompare(w io.Writer, res *compare.Result) error {
	if res == nil {
		return fmt.Errorf("render compare: nil result")
	}
	var b strings.Builder

	b.WriteString(styleTitle.Render("lensyxe compare"))
	b.WriteByte('\n')
	b.WriteString(styleDim.Render(fmt.Sprintf("repo    %s", res.Root)))
	b.WriteByte('\n')
	b.WriteByte('\n')

	// Side-by-side revision header.
	writeRevisionRow(&b, res.A, res.B)
	b.WriteByte('\n')
	b.WriteString(rule())

	// Headline score movement.
	deltaStyle := scoreStyle(mapDeltaToScore(res.ScoreDelta))
	b.WriteString("\n")
	b.WriteString(styleHeader.Render("HEALTH SCORE"))
	b.WriteByte('\n')
	fmt.Fprintf(&b, "  %s -> %s   %s   %s\n",
		scoreStyle(res.ScoreA).Render(fmt.Sprintf("%.1f", res.ScoreA)),
		scoreStyle(res.ScoreB).Render(fmt.Sprintf("%.1f", res.ScoreB)),
		scoreStyle(res.ScoreA).Render(res.GradeA),
		deltaStyle.Render(fmt.Sprintf("(%+.1f)", res.ScoreDelta)))
	b.WriteString(styleDim.Render("  " + res.Verdict))
	b.WriteByte('\n')

	// The composite score here is not the same measure as `lensyxe analyze`'s,
	// and the difference is large enough to mislead.
	//
	// Both revisions are materialised with `git archive`, which produces a
	// directory with no .git in it. Maintainability is read from Git history, so
	// it is never measurable here: its weight is redistributed across the
	// dimensions that could be measured, which moves the absolute score. On this
	// repository, compare reports 65.0 for a commit that analyze scores 67.3.
	//
	// The delta is unaffected -- both sides are measured the same way -- so the
	// comparison remains valid. Only the absolute number is on a different scale,
	// and saying so is cheaper than a user diffing the two outputs and concluding
	// the tool is inconsistent with itself.
	b.WriteString(styleDim.Render("  note  Maintainability is not measured: revisions are exported" +
		" without Git history, so its weight is redistributed."))
	b.WriteByte('\n')
	b.WriteByte('\n')

	if len(res.Metrics) > 0 {
		b.WriteString("  metric deltas\n")
		writeTable(&b, []string{"metric", "from", "to", "delta"},
			func(i int) []string {
				m := res.Metrics[i]
				delta := fmt.Sprintf("%+.1f", m.Delta)
				if m.Better > 0 {
					delta = styleGood.Render(delta)
				} else if m.Better < 0 {
					delta = styleBad.Render(delta)
				}
				return []string{m.Label,
					trimUnit(m.A, m.Unit),
					trimUnit(m.B, m.Unit),
					delta}
			}, len(res.Metrics), []int{0})
		b.WriteByte('\n')
	}

	writeCompareRisks(&b, res)
	writeFooterCompare(&b, res)

	if _, err := io.WriteString(w, b.String()); err != nil {
		return fmt.Errorf("render compare terminal: %w", err)
	}
	return nil
}

// writeRevisionRow renders the A and B revision headers side by side.
func writeRevisionRow(b *strings.Builder, revA, revB compare.RevisionInfo) {
	left := fmt.Sprintf("A  %-12s %s", revA.ShortSHA, truncate(revA.Ref, 20))
	right := fmt.Sprintf("B  %-12s %s", revB.ShortSHA, truncate(revB.Ref, 20))
	fmt.Fprintf(b, "  %-40s %s\n", left, right)
	if revA.Subject != "" || revB.Subject != "" {
		fmt.Fprintf(b, "  %-40s %s\n",
			styleDim.Render(truncate(revA.Subject, 40)),
			styleDim.Render(truncate(revB.Subject, 40)))
	}
}

// writeCompareRisks renders the three risk buckets. An unchanged comparison
// prints a short note rather than an empty heading.
func writeCompareRisks(b *strings.Builder, res *compare.Result) {
	if len(res.RisksAdded) == 0 && len(res.RisksResolved) == 0 && len(res.RisksChanged) == 0 {
		b.WriteString(sectionTitle("RISK DIFF"))
		b.WriteString(styleGood.Render("  no risk changes"))
		b.WriteString("\n\n")
		return
	}

	if len(res.RisksAdded) > 0 {
		b.WriteString(sectionTitle(fmt.Sprintf("NEW RISKS (%d)", len(res.RisksAdded))))
		for _, r := range res.RisksAdded {
			b.WriteString("  " + r.Severity.Emoji() + " " + severityBadge(r.Severity) + " " +
				styleLabel.Render(r.Title) + styleDim.Render(fmt.Sprintf("  (-%.1f pts)", r.Impact)))
			b.WriteByte('\n')
			if r.Subject != "" {
				b.WriteString(styleDim.Render("    subject  " + r.Subject))
				b.WriteByte('\n')
			}
			// Each wrapped line is rendered separately: rendering a multi-line
			// block in one call pads every line to the block width, which
			// leaves ragged trailing whitespace in the output.
			for _, line := range strings.Split(wrap(r.Detail, 66, ""), "\n") {
				b.WriteString(styleDim.Render("    " + strings.TrimRight(line, " ")))
				b.WriteByte('\n')
			}
		}
		b.WriteByte('\n')
	}

	if len(res.RisksResolved) > 0 {
		b.WriteString(sectionTitle(fmt.Sprintf("RESOLVED RISKS (%d)", len(res.RisksResolved))))
		for _, r := range res.RisksResolved {
			b.WriteString("  " + styleGood.Render("FIXED") + " " + r.Title)
			b.WriteByte('\n')
			if r.Subject != "" {
				b.WriteString(styleDim.Render("    subject  " + r.Subject))
				b.WriteByte('\n')
			}
		}
		b.WriteByte('\n')
	}

	if len(res.RisksChanged) > 0 {
		b.WriteString(sectionTitle(fmt.Sprintf("CHANGED RISKS (%d)", len(res.RisksChanged))))
		writeTable(b, []string{"risk", "severity", "impact delta"},
			func(i int) []string {
				c := res.RisksChanged[i]
				sev := string(c.Severity) + " -> " + string(c.After)
				delta := fmt.Sprintf("%+.1f", c.Delta)
				if c.Better > 0 {
					delta = styleGood.Render(delta)
				} else {
					delta = styleBad.Render(delta)
				}
				return []string{c.Title, sev, delta}
			}, len(res.RisksChanged), []int{0})
		b.WriteByte('\n')
	}
}

func writeFooterCompare(b *strings.Builder, res *compare.Result) {
	b.WriteString(rule())
	b.WriteString(styleDim.Render(fmt.Sprintf(
		"schema v%s - %s", res.SchemaVersion, res.GradeChange)))
	b.WriteByte('\n')
}

// mapDeltaToScore maps a delta to a representative score purely for color
// selection, so a regression reads red and an improvement reads green.
func mapDeltaToScore(delta float64) float64 {
	switch {
	case delta < -10:
		return 40
	case delta < 0:
		return 60
	default:
		return 90
	}
}

// trimUnit renders a metric value compactly for the terminal table, which has
// no unit column of its own.
func trimUnit(v float64, unit string) string {
	if v == float64(int64(v)) {
		return fmt.Sprintf("%d", int64(v))
	}
	return fmt.Sprintf("%.1f", v)
}

// wrap breaks detail text onto continuation lines with an indent.
//
// Continuation lines are indented to match the caller's own prefix rather than
// to a fixed column, since the caller already adds its leading whitespace.
func wrap(s string, width int, indent string) string {
	if len(s) <= width {
		return s
	}
	var out strings.Builder
	line := ""
	for _, word := range strings.Fields(s) {
		if line != "" && len(line)+1+len(word) > width {
			out.WriteString(line + "\n" + indent)
			line = word
			continue
		}
		if line == "" {
			line = word
		} else {
			line += " " + word
		}
	}
	out.WriteString(line)
	return out.String()
}

func truncate(s string, max int) string {
	if len(s) <= max {
		return s
	}
	if max <= 1 {
		return s[:max]
	}
	return s[:max-1] + "…"
}
